package com.amit.collabdoc.model;

import jakarta.persistence.*;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Represents a User entity in the database.
 * The @Entity annotation tells Spring Data JPA that this class
 * is a table (named "users") in our database.
 * * This version is written without Lombok to show the
 * explicit constructors, getters, and setters.
 */
@Entity
@Table(name = "users")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true, nullable = false)
    private String username;

    @Column(unique = true, nullable = false)
    private String email;

    @Column(nullable = false)
    private String password;



    // A user can own many documents
    @OneToMany(
            mappedBy = "owner", // "owner" is the field in the Document class
            cascade = CascadeType.ALL, // When a user is deleted, their documents are also deleted
            orphanRemoval = true,
            fetch = FetchType.LAZY
    )
    private Set<Document> ownedDocuments;

    // A user can have many permissions on different documents
    @OneToMany(
            mappedBy = "user", // "user" is the field in the DocumentPermission class
            cascade = CascadeType.ALL,
            orphanRemoval = true,
            fetch = FetchType.LAZY
    )
    private Set<DocumentPermission> permissions;


    /**
     * No-argument constructor.
     * JPA requires this to create instances of the entity.
     */
    public User() {
        // Initialize the new sets
        this.ownedDocuments = new HashSet<>();
        this.permissions = new HashSet<>();
    }

    /**
     * Convenience constructor for creating a new user (e.g., during registration).
     * The ID is not included as it will be auto-generated by the database.
     */
    public User(String username, String email, String password) {
        this.username = username;
        this.email = email;
        this.password = password;
        // Initialize the new sets
        this.ownedDocuments = new HashSet<>();
        this.permissions = new HashSet<>();
    }

    // --- Getters and Setters ---
    // (Existing getters/setters for id, username, email, password...)

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }



    public Set<Document> getOwnedDocuments() {
        return ownedDocuments;
    }

    public void setOwnedDocuments(Set<Document> ownedDocuments) {
        this.ownedDocuments = ownedDocuments;
    }

    public Set<DocumentPermission> getPermissions() {
        return permissions;
    }

    public void setPermissions(Set<DocumentPermission> permissions) {
        this.permissions = permissions;
    }




    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        // Once an entity has an ID, that's the most reliable check
        return id != null && Objects.equals(id, user.id);
    }

    @Override
    public int hashCode() {
        // Use the ID for hashing if it exists, otherwise use the class's hashcode
        return id != null ? Objects.hash(id) : super.hashCode();
    }

    @Override
    public String toString() {
        // Provides a clean string representation for logging.

        return "User{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}

